### ISSUE TITLE
Tick boxes (circles) not showing on chrome on macos

### ISSUE THREAD

**Issue by ghufransyed** [day8/re-frame#722]
I am running macos 11.2.3, chrome  90.0.4430.93 (Official Build) (x86_64), safari 14.0.3 (16610.4.3.1.7). 

In safari (right side of screenshot below), the check-circles show up, and show the checkmark when clicked. In Chrome (left side of screenshot below), the check-circles don't show up, and neither does the checkmark when clicked - but the state of the todo does change as expected to strikethrough text. 

<img width="1908" alt="Screen Shot 2021-05-08 at 4 40 36 PM" src="https://user-images.githubusercontent.com/5146803/117556301-26b68200-b01c-11eb-939f-86f05688fc1e.png">

**Comment by jtkDvlp** [comment]
Did you check the dom, are the expected elements given, maybe an css issue?

**Comment by tavlarides** [comment]
It seems that the problem is in todos.css and specifically in 
```css
#todo-list li .toggle:after
#todo-list li .toggle:checked:after
```
Both of these are using inline svg.


SVG content needs to be url-escaped,
so replacing the `#` character with `%23` seems to fix the issue.

Modified lines in todos.css:
```css
#todo-list li .toggle:after {
    content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="%23ededed" stroke-width="3"/></svg>');
}

#todo-list li .toggle:checked:after {
    content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="%23bddad5" stroke-width="3"/><path fill="%235dc2af" d="M72 25L42 71 27 56l-4 4 20 20 34-52z"/></svg>');
}
```
<img width="562" alt="Screen Shot 2021-09-26 at 11 18 25 AM" src="https://user-images.githubusercontent.com/83822/134799774-e68115c6-d876-4507-a354-e726e9a027a3.png">
